services:
  chesspoint:
    image: node:22-slim
    container_name: chesspoint
    user: "${HOST_UID}:${HOST_GID}"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: /bin/sh -c "npm install && npm run ${COMMAND}"
